name: Build VideoWallpaper

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild VideoWallpaper.sln /p:Configuration=Release /p:Platform=Win32

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: VideoWallpaper
          path: Release/**
